apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: devops-app
  endpoints:
    - port: http
      path: /actuator/health
      interval: 15s